# Generated by Django 2.0 on 2020-08-10 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VideoUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('video_link', models.CharField(max_length=1000)),
                ('thumbnail_link', models.CharField(max_length=1000)),
                ('descripion', models.TextField()),
                ('dept_head', models.CharField(max_length=100)),
            ],
        ),
    ]
